{%set name = "dbfread" %}
{%set version = "1.1.1" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "f1fdd09c28cb46412bb61dc8b70668e4c60c86f8ef190ed1bc919042f65d0784" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - dbfread

about:
  home: https://dbfread.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'read data from dbf files'
  dev_url: https://github.com/olemb/dbfread
  doc_url: https://dbfread.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
