travis:
  secure:
    BINSTAR_TOKEN: UQrGbRG4GooeHIZMvrSc4sQRPX5WHFoF/lnDxCJk0mgAi2JIY/GDyYbqGz9amFesBMFlh2EFD4kxnt4I3GdPhqHNsjPX5fUFW5DP0DrTbUVy7LjZqEfb3skLY5yxNCV1ItXvFmZiE9Ct29U5gR7ezgpUxJgPpz+VEhx/KAcmEBc4VSmCsdb2sHNp1RlT/M7JEFUfQPZTx/XjNjqABW5n0hd2r4uH3Tgo8SIZmdHR3kqVMBv2e4OE8o1LYzZrViEimxJhzPIA66jKuJvyYAyJE2AMssWL3Af8/01xIK8A/kKe09yAbGuDyq7B3u63C3jzXodWSOdwJZ1FfT6FQSLXOccL4GRRQs4eVD0L5SBa8ywFGE/C9cz8Ac1j5gBzo4p0SbiAp0jGKyDDinaG2EGMs2pye9orrBld3JJpadw88dtbuqRZVO/65dpKuWIQQa44/4eaXBg/65Kg7G5s3ox103J3vnh22JYv5oNs/dUXD6L/1Qt1veivcGD/C1vW+IS5tEtbwvK+iHQd3zhwYlcFp119Cf/onKOEuWh/Ge8EuMTJ2xejpFud4L8XPwch7haVd1tR+q4WS0aImS9P3iPrQV2fpTTXKfMZYSjk3R3Ju7gnEETm+W+7NawuB7YAMEn4Pe3XqOgZEZtP4l6G1oVVK4y6stue7KbwKZt49qoubQ8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
